---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-2-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/test6-janus/my-quarkus-app-2-gitops